/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSkatingRouteImport } from './routes/app.skating'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppSkatingStatsRouteImport } from './routes/app.skating.stats'
import { Route as AppHabitsIdRouteImport } from './routes/app.habits.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkatingRoute = AppSkatingRouteImport.update({
  id: '/skating',
  path: '/skating',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppSkatingStatsRoute = AppSkatingStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppSkatingRoute,
} as any)
const AppHabitsIdRoute = AppHabitsIdRouteImport.update({
  id: '/habits/$id',
  path: '/habits/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skating': typeof AppSkatingRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/habits/$id': typeof AppHabitsIdRoute
  '/app/skating/stats': typeof AppSkatingStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skating': typeof AppSkatingRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/habits/$id': typeof AppHabitsIdRoute
  '/app/skating/stats': typeof AppSkatingStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/notes': typeof AppNotesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skating': typeof AppSkatingRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/habits/$id': typeof AppHabitsIdRoute
  '/app/skating/stats': typeof AppSkatingStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/notes'
    | '/app/settings'
    | '/app/skating'
    | '/app/'
    | '/app/habits/$id'
    | '/app/skating/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/notes'
    | '/app/settings'
    | '/app/skating'
    | '/app'
    | '/app/habits/$id'
    | '/app/skating/stats'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/notes'
    | '/app/settings'
    | '/app/skating'
    | '/app/'
    | '/app/habits/$id'
    | '/app/skating/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skating': {
      id: '/app/skating'
      path: '/skating'
      fullPath: '/app/skating'
      preLoaderRoute: typeof AppSkatingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skating/stats': {
      id: '/app/skating/stats'
      path: '/stats'
      fullPath: '/app/skating/stats'
      preLoaderRoute: typeof AppSkatingStatsRouteImport
      parentRoute: typeof AppSkatingRoute
    }
    '/app/habits/$id': {
      id: '/app/habits/$id'
      path: '/habits/$id'
      fullPath: '/app/habits/$id'
      preLoaderRoute: typeof AppHabitsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSkatingRouteChildren {
  AppSkatingStatsRoute: typeof AppSkatingStatsRoute
}

const AppSkatingRouteChildren: AppSkatingRouteChildren = {
  AppSkatingStatsRoute: AppSkatingStatsRoute,
}

const AppSkatingRouteWithChildren = AppSkatingRoute._addFileChildren(
  AppSkatingRouteChildren,
)

interface AppRouteChildren {
  AppNotesRoute: typeof AppNotesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkatingRoute: typeof AppSkatingRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppHabitsIdRoute: typeof AppHabitsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotesRoute: AppNotesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkatingRoute: AppSkatingRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppHabitsIdRoute: AppHabitsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
